#
# MIT License
#
# (C) Copyright 2021-2022, 2024 Hewlett Packard Enterprise Development LP
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
apiVersion: v2
name: cray-ims
version: 0.0.0-imsserv-chart
description: Kubernetes resources for cray-ims
keywords:
- Image Management Service
- IMS
home: https://github.com/Cray-HPE/ims
sources:
- https://github.com/Cray-HPE/ims
- https://github.com/Cray-HPE/ims-utils
- https://github.com/Cray-HPE/ims-kiwi-ng-opensuse-x86_64-builder
- https://github.com/Cray-HPE/ims-sshd
dependencies:
- name: cray-service
  version: ^11.0.0
  repository: https://artifactory.algol60.net/artifactory/csm-helm-charts/
maintainers:
- name: ecozzi-hpe
  email: eric.cozzi@hpe.com
appVersion: 0.0.0-imsserv-docker
annotations:
  artifacthub.io/images: |
    - name: cray-ims-service
      image: artifactory.algol60.net/csm-docker/S-T-A-B-L-E/cray-ims-service:0.0.0-imsserv-docker
    - name: cray-ims-utils
      image: artifactory.algol60.net/csm-docker/stable/cray-ims-utils:0.0.0-imsutils
    - name: cray-ims-kiwi-ng-opensuse-x86_64-builder
      image: artifactory.algol60.net/csm-docker/stable/cray-ims-kiwi-ng-opensuse-x86_64-builder:0.0.0-imskiwi
    - name: cray-ims-sshd
      image: artifactory.algol60.net/csm-docker/stable/cray-ims-sshd:0.0.0-imssshd
    - name: alpine
      image: alpine:latest
  artifacthub.io/license: MIT
