apiVersion: v2
name: cray-ims
version: 0.0.0-imsserv
description: Kubernetes resources for cray-ims
keywords:
- Image Management Service
- IMS
home: https://github.com/Cray-HPE/ims
sources:
- https://github.com/Cray-HPE/ims
- https://github.com/Cray-HPE/ims-utils
- https://github.com/Cray-HPE/ims-kiwi-ng-opensuse-x86_64-builder
- https://github.com/Cray-HPE/ims-sshd
dependencies:
- name: cray-service
  version: ^7.0.0
  repository: https://artifactory.algol60.net/artifactory/csm-helm-charts/
maintainers:
- name: ecozzi-hpe
  email: eric.cozzi@hpe.com
appVersion: 0.0.0-imsserv
annotations:
  artifacthub.io/images: |
    - name: cray-ims-service
      image: artifactory.algol60.net/csm-docker/stable/cray-ims-service:0.0.0-imsserv
    - name: cray-ims-utils
      image: artifactory.algol60.net/csm-docker/stable/cray-ims-utils:0.0.0-imsutils
    - name: cray-ims-kiwi-ng-opensuse-x86_64-builder
      image: artifactory.algol60.net/csm-docker/stable/cray-ims-kiwi-ng-opensuse-x86_64-builder:0.0.0-imskiwi
    - name: cray-ims-sshd
      image: artifactory.algol60.net/csm-docker/stable/cray-ims-sshd:0.0.0-imssshd
    - name: alpine
      image: alpine:latest
  artifacthub.io/license: MIT
