#
# MIT License
#
# (C) Copyright 2021-2022 Hewlett Packard Enterprise Development LP
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
# Please refer to https://github.com/Cray-HPE/base-charts/tree/master/kubernetes/cray-service/values.yaml
# for more info on values you can set/override
# Note that cray-service.containers[*].image and cray-service.initContainers[*].image map values are one of the only structures that
# differ from the standard kubernetes container spec:
# image:
#   repository: ""
#   tag: "" (default = "latest")
#   pullPolicy: "" (default = "IfNotPresent")

gunicorn:
  worker_timeout: "3600"

s3:
  endpoint: ~
  ims_bucket: "ims"
  boot_images_bucket: "boot-images"
  protocol: "http"
  connect_timeout: "60"
  read_timeout: "60"

alpine:
  image:
    repository: alpine
    tag: latest
    pullPolicy: IfNotPresent

ims_config:
  cray_ims_job_namespace: "ims"
  cray_ims_service_namespace: "services"

cray_ims_utils:
  image:
    repository: "artifactory.algol60.net/csm-docker/stable/cray-ims-utils"
    tag: "0.0.0-imsutils"
    imagePullPolicy: IfNotPresent

cray_ims_kiwi_ng_opensuse_x86_64_builder:
  image:
    repository: "artifactory.algol60.net/csm-docker/stable/cray-ims-kiwi-ng-opensuse-x86_64-builder"
    tag: "0.0.0-imskiwi"
    imagePullPolicy: IfNotPresent

cray_ims_sshd:
  image:
    repository: "artifactory.algol60.net/csm-docker/stable/cray-ims-sshd"
    tag: "0.0.0-imssshd"
    imagePullPolicy: IfNotPresent

cray_ims_packer_opensuse_x86_64_builder:
  image:
    repository: "artifactory.algol60.net/csm-docker/stable/cray-ims-packer-opensuse-x86_64-builder"
    tag: "latest"
    imagePullPolicy: IfNotPresent

api_gw:
  api_gw_service_name: "istio-ingressgateway"
  api_gw_service_namespace: "istio-system"

keycloak:
  keycloak_admin_client_auth_secret_name: "admin-client-auth"

customer_access:
  shasta_domain: "shasta.local"
  access_pool: "customer-management"
  subnet_name: "cmn"

cray-service:
  type: Deployment
  nameOverride: cray-ims

  containers:
    cray-ims:
      name: cray-ims
      image:
        repository: artifactory.algol60.net/csm-docker/S-T-A-B-L-E/cray-ims-service
        # tag defaults to chart appVersion
      ports:
        - name: http
          containerPort: 9000
      envFrom:
        - configMapRef:
            name: ims-config
      env:
        - name: S3_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: ims-s3-credentials
              key: access_key
        - name: S3_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: ims-s3-credentials
              key: secret_key
        - name: S3_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: ims-s3-credentials
              key: s3_endpoint
        - name: S3_SSL_VALIDATE
          valueFrom:
            secretKeyRef:
              name: ims-s3-credentials
              key: ssl_validate
      volumeMounts:
        - mountPath: /var/ims/data
          name: cray-ims-data
        - name: ca-vol
          mountPath: /mnt/ca-vol
        - name: v2-image-create-kiwi-ng-job-template-vol
          mountPath: /mnt/ims/v2/job_templates/create/kiwi-ng/
        - name: v2-image-create-packer-job-template-vol
          mountPath: /mnt/ims/v2/job_templates/create/packer/
        - name: v2-image-customize-job-template-vol
          mountPath: /mnt/ims/v2/job_templates/customize
      livenessProbe:
        httpGet:
          port: 9000
          path: /healthz/live
        initialDelaySeconds: 5
        periodSeconds: 60
        timeoutSeconds: 45
        failureThreshold: 5
        successThreshold: 1
      readinessProbe:
        httpGet:
          port: 9000
          path: /healthz/ready
        initialDelaySeconds: 5
        periodSeconds: 60
        timeoutSeconds: 45
        failureThreshold: 5
        successThreshold: 1
  volumes:
    cray-ims-data:
      name: cray-ims-data
      persistentVolumeClaim:
        claimName: cray-ims-data-claim
    ca-vol:
      name: ca-vol
      configMap:
        name: cray-configmap-ca-public-key
    v2-image-create-kiwi-ng-job-template-vol:
      name: v2-image-create-kiwi-ng-job-template-vol
      configMap:
        name: cray-configmap-ims-v2-image-create-kiwi-ng
    v2-image-create-packer-job-template-vol:
      name: v2-image-create-packer-job-template-vol
      configMap:
        name: cray-configmap-ims-v2-image-create-packer
    v2-image-customize-job-template-vol:
      name: v2-image-customize-job-template-vol
      configMap:
        name: cray-configmap-ims-v2-image-customize

  serviceAccountName: ims-service-launch-job

  storageClass: ceph-cephfs-external
  persistentVolumeClaims:
    data-claim:
      name: data-claim  # will be prefixed with cray-ims-
      accessModes:
        - ReadWriteMany
      resources:
        requests:
          storage: 10Gi

  ingress:
    enabled: true
    prefix: /apis/ims/
    uri: /

  strategy:
    type: Recreate
