# Please refer to https://github.com/Cray-HPE/base-charts/tree/master/kubernetes/cray-service/values.yaml
# for more info on values you can set/override
# Note that cray-service.containers[*].image and cray-service.initContainers[*].image map values are one of the only structures that
# differ from the standard kubernetes container spec:
# image:
#   repository: ""
#   tag: "" (default = "latest")
#   pullPolicy: "" (default = "IfNotPresent")

s3:
  endpoint: ~
  ims_bucket: "ims"
  boot_images_bucket: "boot-images"
  protocol: "http"
  connect_timeout: "60"
  read_timeout: "60"

ims_config:
  cray_ims_job_namespace: "ims"
  cray_ims_service_namespace: "services"

  # {cray_ims_utils_image_org}/{cray_ims_utils_image_name}:{cray_ims_utils_image_version}
  cray_ims_utils_image_org: "cray"
  cray_ims_utils_image_name: "cray-ims-utils"
  cray_ims_utils_image_version: "IMS_UTILS_VERSION"

  # {cray_ims_kiwi_ng_opensuse_x86_64_builder_image_org}/{`cray_ims_kiwi_ng_opensuse_x86_64_builder_image_name`}:{cray_ims_kiwi_ng_opensuse_x86_64_builder_image_version}
  cray_ims_kiwi_ng_opensuse_x86_64_builder_image_org: "cray"
  cray_ims_kiwi_ng_opensuse_x86_64_builder_image_name: "cray-ims-kiwi-ng-opensuse-x86_64-builder"
  cray_ims_kiwi_ng_opensuse_x86_64_builder_image_version: "IMS_KIWI_NG_VERSION"

  # {cray_ims_sshd_image_org}/{cray_ims_sshd_image_name}:{cray_ims_sshd_image_version}
  cray_ims_sshd_image_org: "cray"
  cray_ims_sshd_image_name: "cray-ims-sshd"
  cray_ims_sshd_image_version: "IMS_SSHD_VERSION"

api_gw:
  api_gw_service_name: "istio-ingressgateway"
  api_gw_service_namespace: "istio-system"

keycloak:
  keycloak_admin_client_auth_secret_name: "admin-client-auth"

customer_access:
  shasta_domain: "shasta.local"
  access_pool: "customer-access"

cray-service:
  type: Deployment
  nameOverride: cray-ims

  containers:
    cray-ims:
      name: cray-ims
      image:
        repository: cray/cray-ims-service
      ports:
        - name: http
          containerPort: 9000
      envFrom:
        - configMapRef:
            name: ims-config
      env:
        - name: S3_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: ims-s3-credentials
              key: access_key
        - name: S3_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: ims-s3-credentials
              key: secret_key
        - name: S3_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: ims-s3-credentials
              key: s3_endpoint
        - name: S3_SSL_VALIDATE
          valueFrom:
            secretKeyRef:
              name: ims-s3-credentials
              key: ssl_validate
      volumeMounts:
        - mountPath: /var/ims/data
          name: cray-ims-data
        - name: ca-vol
          mountPath: /mnt/ca-vol
        - name: v2-image-create-kiwi-ng-job-template-vol
          mountPath: /mnt/ims/v2/job_templates/create/kiwi-ng/
        - name: v2-image-create-packer-job-template-vol
          mountPath: /mnt/ims/v2/job_templates/create/packer/
        - name: v2-image-customize-job-template-vol
          mountPath: /mnt/ims/v2/job_templates/customize
      livenessProbe:
        httpGet:
          port: 9000
          path: /healthz/live
        initialDelaySeconds: 5
        periodSeconds: 60
        timeoutSeconds: 5
        failureThreshold: 3
      readinessProbe:
        httpGet:
          port: 9000
          path: /healthz/ready
        initialDelaySeconds: 5
        periodSeconds: 10
        timeoutSeconds: 5
        failureThreshold: 3
  volumes:
    cray-ims-data:
      name: cray-ims-data
      persistentVolumeClaim:
        claimName: cray-ims-data-claim
    ca-vol:
      name: ca-vol
      configMap:
        name: cray-configmap-ca-public-key
    v2-image-create-kiwi-ng-job-template-vol:
      name: v2-image-create-kiwi-ng-job-template-vol
      configMap:
        name: cray-configmap-ims-v2-image-create-kiwi-ng
    v2-image-create-packer-job-template-vol:
      name: v2-image-create-packer-job-template-vol
      configMap:
        name: cray-configmap-ims-v2-image-create-packer
    v2-image-customize-job-template-vol:
      name: v2-image-customize-job-template-vol
      configMap:
        name: cray-configmap-ims-v2-image-customize

  serviceAccountName: ims-service-launch-job

  storageClass: ceph-cephfs-external
  persistentVolumeClaims:
    data-claim:
      name: data-claim # will be prefixed with cray-ims-
      accessModes:
        - ReadWriteMany
      resources:
        requests:
          storage: 10Gi

  ingress:
    enabled: true
    prefix: /apis/ims/
    uri: /

  strategy:
    type: Recreate
