# Copyright 2019, Cray Inc. All Rights Reserved.
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: ims-service-launch-job
  namespace: {{ .Values.ims_config.cray_ims_service_namespace }}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ims-service-launch-job
rules:
  - apiGroups: [""]
    resources: ["services","configmaps","roles"]
    verbs: ["get", "create", "delete"]
  - apiGroups: ["networking.istio.io"]
    resources: ["destinationrules"]
    verbs: ["get", "create", "delete"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "create", "delete", "patch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ims-service-launch-job
subjects:
  - kind: ServiceAccount
    name: ims-service-launch-job
    namespace: {{ .Values.ims_config.cray_ims_service_namespace }}
roleRef:
  kind: ClusterRole
  name: ims-service-launch-job
  apiGroup: rbac.authorization.k8s.io
